definitions:
  models.Fact:
    properties:
      ID:
        type: integer
      fact:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /facts/random:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Random fact
          schema:
            $ref: '#/definitions/models.Fact'
        "404":
          description: No facts available
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get random fact
      tags:
      - facts
swagger: "2.0"
